### ISSUE TITLE
Is use in browser javascript possible?

### ISSUE THREAD

**Issue by abulka** [jmerle/node-icecream#1]
I'd like to use ice-cream in my browser app, which uses npm packages via a bundler (esbuild, in my case).  Unfortunately `esbuild` complains with
```
node-icecream/index.js:1:19: error: Could not resolve "fs" (set platform to "node" when building for node)
```
which makes sense since the browser is not able to access the filesystem. Perhaps a fork of ice-cream with `fs` features removed is the only way around this?

**Comment by jmerle** [comment]
This package was a little toy project of mine 3 years ago, it's not maintained anymore. I indeed recommend forking the project if you want this feature.

**Comment by Leftium** [comment]
My [@leftium/gg](https://github.com/Leftium/gg) module works in the browser! Its passthrough debugging API is inspired by icecream (and https://www.npmjs.com/package/debug)

At *build-time* an optional Vite plugin rewrites calls to gg() with the meta info (expression, function name, filename, line number, column number, etc...) So `fs` is not needed at runtime.

**Live demo:** https://gg.leftium.com/?gg

**Screenshot:** (The GG dev console is optional, but supports richer output.)

<img width="854" height="889" alt="Image" src="https://github.com/user-attachments/assets/56b013d3-c194-46c5-b025-f2fd5dcb793b" />
